### ISSUE TITLE
Folia 1.21 报错

### ISSUE THREAD

**Issue by x1aoren** [ArtisticCraft/quark-public#1]
[13:22:21 INFO]:  ______   __  __   ______   ______   __  __
[13:22:21 INFO]: /\  __ \ /\ \/\ \ /\  __ \ /\  == \ /\ \/ /
[13:22:21 INFO]: \ \ \/\_\\ \ \_\ \\ \  __ \\ \  __< \ \  _"-.
[13:22:21 INFO]:  \ \___\_\\ \_____\\ \_\ \_\\ \_\ \_\\ \_\ \_\
[13:22:21 INFO]:   \/___/_/ \/_____/ \/_/\/_/ \/_/ /_/ \/_/\/_/       v0.63.15
[13:22:21 INFO]: ------------------------------------------------------------
[13:22:21 INFO]: Artifact by GrassBlock2022, Copyright [C]TBSTMC 2024.
[13:22:21 INFO]:
[13:22:21 INFO]: Quark核心检测到您正在使用Folia服务端!
[13:22:21 INFO]:   Folia兼容已自动启用。我们不保证任何功能的可用!
[13:22:21 INFO]: Quark core detected you are using Folia Server!
[13:22:21 INFO]:   Folia compat are automatically enabled.We do NOT ensure any feature's availability!
[13:22:21 INFO]:
[13:22:21 INFO]: [QuarkCore] Bootstrap initialization completed. (27 ms)
[13:22:21 INFO]: [QuarkCore] detected server platform: folia
[13:22:21 INFO]: [QuarkCore] using PlaceholderAPI text formatter
[13:22:21 INFO]: [QuarkCore] disabled fastboot, loading full jar...
[13:22:21 ERROR]: Error occurred while enabling quark v0.63.15 (Is it up to date?)
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap.run(Bootstrap.java:45) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Quark.onEnable(Quark.java:92) ~[[q][夸克]quark.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:595) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:780) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:527) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:331) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap.run(Bootstrap.java:43) ~[[q][夸克]quark.jar:?]
        ... 13 more
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: D:\ASIO2核心\plugins\quark.jar
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap$BootOperations.loadFullJar(Bootstrap.java:130) ~[[q][夸克]quark.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap.run(Bootstrap.java:43) ~[[q][夸克]quark.jar:?]
        ... 13 more
Caused by: java.nio.file.NoSuchFileException: D:\ASIO2核心\plugins\quark.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:197) ~[?:?]
        at java.base/java.nio.file.Files.readAttributes(Files.java:1853) ~[?:?]
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1445) ~[?:?]
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724) ~[?:?]
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251) ~[?:?]
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180) ~[?:?]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:345) ~[?:?]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:316) ~[?:?]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:282) ~[?:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap$BootOperations.loadFullJar(Bootstrap.java:108) ~[[q][夸克]quark.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap.run(Bootstrap.java:43) ~[[q][夸克]quark.jar:?]
        ... 13 more
[13:22:21 INFO]: [QuarkCore] Disabling quark v0.63.15
[13:22:21 ERROR]: Error occurred while disabling quark v0.63.15
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap.run(Bootstrap.java:45) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Quark.onDisable(Quark.java:103) ~[[q][夸克]quark.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:595) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:780) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:527) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:331) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[luminol-1.21.jar:1.21-DEV-b27cf96]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap.run(Bootstrap.java:43) ~[[q][夸克]quark.jar:?]
        ... 16 more
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:159) ~[?:?]
        at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.framework.service.ServiceManager$Impl.unregisterService(ServiceManager.java:160) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.framework.service.ServiceManager.unregister(ServiceManager.java:26) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.framework.service.Service.stopBase(Service.java:27) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap$StopOperations.stopService(Bootstrap.java:161) ~[[q][夸克]quark.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap.run(Bootstrap.java:43) ~[[q][夸克]quark.jar:?]
        ... 16 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.tbstcraft.quark.internal.permission.PermissionService.create(String)" because the return value of "org.tbstcraft.quark.framework.service.ServiceHolder.get()" is null
        at [q][夸克]quark.jar/org.tbstcraft.quark.internal.permission.PermissionService.createPermission(PermissionService.java:56) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.foundation.command.AbstractCommand.init(AbstractCommand.java:74) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.foundation.command.CoreCommand.<init>(CoreCommand.java:10) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.internal.LocaleService$LanguageDecideCommand.<init>(LocaleService.java:100) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.internal.LocaleService.<clinit>(LocaleService.java:28) ~[[q][夸克]quark.jar:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:159) ~[?:?]
        at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:726) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.framework.service.ServiceManager$Impl.unregisterService(ServiceManager.java:160) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.framework.service.ServiceManager.unregister(ServiceManager.java:26) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.framework.service.Service.stopBase(Service.java:27) ~[[q][夸克]quark.jar:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap$StopOperations.stopService(Bootstrap.java:161) ~[[q][夸克]quark.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at [q][夸克]quark.jar/org.tbstcraft.quark.Bootstrap.run(Bootstrap.java:43) ~[[q][夸克]quark.jar:?]
        ... 16 more

**Comment by Grass-block** [comment]
请不要重命名任何文件。
这可能会导致核心判断失误。

计划更改：不依赖文件名的核心判断

**Comment by Grass-block** [comment]
仓库位置已更改，请移步至https://github.com/Grass-block/Quark-Plugin

**Comment by Grass-block** [comment]
0.64.10 已修复 欢迎下载
